trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: BackendTests
  displayName: 'Backend Tests'
  jobs:
  - job: Pytest
    displayName: 'Run Pytest'

    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        echo "Ubicación actual:"
        pwd

        echo "Contenido del repositorio:"
        ls -R

        python -m pip install --upgrade pip

        pip install -r backend/requirements.txt

        export PYTHONPATH=$(pwd)

        pytest backend/app/tests -v
      displayName: 'Run Backend Tests'

- stage: FrontendTests
  displayName: 'Frontend Tests'
  dependsOn: BackendTests
  condition: succeeded()

  jobs:

  - job: Vitest
    displayName: 'Run Vitest'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'

    - script: |
        cd frontend/medical-frontend

        npm install

        npm test -- --run
      displayName: 'Run Frontend Tests'