sonar.projectKey=medical-system
sonar.projectName=Medical System
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/medical-frontend/src
sonar.tests=backend/app/tests,frontend/medical-frontend/src/tests,e2e/tests

sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/*.pyc
sonar.test.inclusions=**/test_*.py,**/*.test.jsx,**/*.spec.js

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/medical-frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
